### ISSUE TITLE
Etapa 2

### ISSUE THREAD

**Issue by Viniciuszevedo** [ICEI-PUC-Minas-PPC-CC/ppc-cc-2024-2-ment2-noite1-programadores_kids#1]
Precisamos criar a segunda etapa!

Simbora turma

**Comment by Viniciuszevedo** [comment]
Comenta aí por favor, pra saber se está funcionando...

**Comment by pedrosarto** [comment]
Está funcionando

**Comment by Romulo-Cr** [comment]
Opa

**Comment by Romulo-Cr** [comment]
Vai Brasil

**Comment by Viniciuszevedo** [comment]
Boa noite

**Comment by leonardoeliasf** [comment]
TESTE

**Comment by Viniciuszevedo** [comment]
Romulo que enviou

*Opção 1:*

Aula de programação em *"linguagem indefinida"* para crianças.


*Aula um:* definição de conteúdos e projetos que serão abordados e trabalhados durante  as aulas e introdução ao conteúdo básico.

*Aula dois em diante:* execução de tarefas e apresentação de novos conteúdos.

*Última aula:*  criação de um projeto que engloba todos os assuntos abordados durante as aulas.
 *Opção 2:*

Aula de programação e projetos de LPHS para crianças.

*Aula um:* Introdução aos conteúdos abordados durante as aulas e programação do primeiro projeto que deverá ser montado na aula seguinte.

*Aula dois:* criação do hardwere do projeto apresentado na primeira aula.

*Aulas seguntes:* Continuar com dias separados para a programação e criação do hardware até a última aula.
 *Dúvidas:* 

1: Qual a idade dos indivíduos?

2: Quantas aulas serão?

3: Em quais dias ocorrerá?

4: Quais recursos estarão disponíveis para a execução de nossas atividades?

5: Recomendações de linguagem para ser utilizado para primeiro contato da criança com a programação.

5: Recomendações de abordagens para um melhor ensino do conteúdo.

**Comment by leonardoeliasf** [comment]
Introdução
O projeto "Programadores Kids" tem como objetivo ensinar fundamentos de programação para crianças e adolescentes de escolas públicas. O projeto surge em um contexto onde a tecnologia está cada vez mais presente no cotidiano, transformando a forma como as pessoas trabalham, se comunicam e resolvem problemas. Contudo, muitos alunos de escolas públicas ainda não possuem acesso adequado à educação tecnológica, o que limita seu desenvolvimento. Assim, este projeto busca promover a inclusão digital, estimular o raciocínio lógico e capacitar os estudantes para interagir com o mundo digital de maneira ativa, ao invés de serem apenas consumidores de tecnologia.

O público-alvo do projeto são crianças e adolescentes entre 10 e 17 anos, alunos de escolas públicas. Essas faixas etárias são particularmente receptivas ao aprendizado de novas habilidades e, ao serem expostas ao ensino de programação, terão a oportunidade de desenvolver competências essenciais, como resolução de problemas, pensamento crítico e criatividade. A inclusão digital é fundamental para preparar esses jovens para o futuro, conforme sugerido por autores como Valente (2017), que destaca a importância da tecnologia na formação educacional.

Problema
A crescente demanda por habilidades tecnológicas no mercado de trabalho e na sociedade não é acompanhada por uma oferta adequada de educação em tecnologia nas escolas públicas brasileiras. Muitos jovens em idade escolar não possuem contato com programação ou sequer têm noções básicas de raciocínio lógico, o que os coloca em desvantagem frente ao mundo digital. A falta de acesso a esse tipo de conhecimento também limita suas oportunidades futuras de emprego e desenvolvimento pessoal, criando uma lacuna de inclusão digital (SANTOS, 2021).

Objetivos
Objetivo Geral:
Capacitar crianças e adolescentes de escolas públicas com conhecimentos básicos de programação, promovendo a inclusão digital e preparando-os para os desafios do futuro.

Objetivos Específicos:

Ensinar os conceitos básicos de lógica de programação e algoritmos de maneira acessível e interativa para os diferentes perfis de alunos das escolas públicas.
Desenvolver atividades práticas que envolvam a criação de pequenos projetos em linguagens de programação voltadas para iniciantes, como Scratch e Python, conforme orientações de Campos (2019).
Estimular o pensamento lógico e a resolução de problemas, incentivando o desenvolvimento de habilidades colaborativas e individuais, conforme estudos de Moura (2020).
Justificativa
A escolha do tema de ensino de programação para crianças e adolescentes de escolas públicas se justifica pela importância crescente da tecnologia na sociedade moderna. Segundo a UNESCO (2022), apenas uma pequena fração dos jovens em países em desenvolvimento tem acesso adequado à educação em tecnologia. Este projeto visa combater essa lacuna, oferecendo educação tecnológica de qualidade, especialmente em escolas públicas, que muitas vezes carecem de recursos nesse campo (SANTOS, 2021).

Estudos mostram que o aprendizado de programação desde cedo pode melhorar significativamente o desempenho escolar em disciplinas como matemática e ciências, além de promover habilidades essenciais para o século XXI, como pensamento crítico e autonomia (VALENTE, 2017). Ao capacitar esses jovens com habilidades tecnológicas, estamos contribuindo para a formação de uma geração mais preparada para os desafios do mercado de trabalho e da cidadania digital.

Público-Alvo:
O público-alvo do projeto são crianças e adolescentes de 10 a 17 anos, que estudam em escolas públicas. Eles apresentam diferentes níveis de acesso à tecnologia: enquanto alguns podem já ter tido contato com computadores e dispositivos móveis, outros podem não ter nenhuma experiência prévia com essas ferramentas. Um dos desafios será lidar com essa diversidade, oferecendo conteúdos que atendam tanto aqueles que são iniciantes quanto aqueles que possuem maior familiaridade com a tecnologia (CAMPOS, 2019).

**Comment by leonardoeliasf** [comment]
Personas
Persona 1: João Pedro Silva

Idade: 12 anos
Naturalidade: São Paulo, SP
Ocupação: Estudante do ensino fundamental em uma escola pública
Atribuições: Participar das atividades escolares e extracurriculares. Responsável por fazer tarefas e aprender novos conteúdos.
Motivações: João é curioso e gosta de tecnologia, especialmente videogames. Ele quer entender como os jogos são feitos e sonha em criar seus próprios jogos no futuro.
Frustrações: João tem dificuldade em se concentrar nas aulas mais teóricas, pois acha o conteúdo muito distante do seu interesse por tecnologia. Ele também tem pouco acesso a computadores e Internet em casa, o que limita seu aprendizado.
Hobbies e História: João adora jogar videogame e passar o tempo assistindo a vídeos sobre tecnologia. Ele gosta de aprender coisas novas, mas prefere quando pode aplicar esse aprendizado em algo prático, como jogos ou projetos de tecnologia.
Persona 2: Maria Fernanda Costa

Idade: 15 anos
Naturalidade: Salvador, BA
Ocupação: Estudante do ensino médio em uma escola pública
Atribuições: Estudar, participar de projetos escolares e ajudar seus pais em casa.
Motivações: Maria tem interesse em aprender programação para se preparar para o futuro. Ela sabe que a área de tecnologia oferece boas oportunidades de emprego e quer desenvolver habilidades que a ajudem a ingressar em uma universidade de tecnologia.
Frustrações: Maria sente que a escola não oferece oportunidades suficientes para o aprendizado de tecnologia. Além disso, ela tem pouca experiência com programação, o que a deixa insegura para começar a aprender.
Hobbies e História: Maria gosta de ler e está sempre pesquisando sobre carreiras e oportunidades educacionais. Seu sonho é ser a primeira pessoa de sua família a ingressar em uma universidade e trabalhar na área de tecnologia.
Histórias de Usuários
Persona 1: João Pedro Silva
Eu como João Pedro quero aprender a programar através de jogos e atividades interativas para tornar o aprendizado mais divertido e interessante.

Eu como João Pedro preciso de acesso fácil a tutoriais e exemplos práticos de programação para entender como os conceitos aprendidos nas aulas podem ser aplicados na criação de jogos simples.

Eu como João Pedro gostaria de ter mais tempo de acesso a computadores na escola para poder praticar mais a programação, já que em casa eu não tenho computador.

Persona 2: Maria Fernanda Costa
Eu como Maria Fernanda quero aprender a programar para me preparar para futuras oportunidades na área de tecnologia para conseguir ingressar em uma universidade e conquistar um bom emprego.

Eu como Maria Fernanda preciso de um ambiente seguro e acessível para praticar programação para desenvolver confiança nas minhas habilidades e entender melhor os conceitos de forma prática.

Eu como Maria Fernanda gostaria de participar de projetos de programação em grupo para melhorar minhas habilidades de trabalho em equipe e aprender com outras pessoas.

**Comment by leonardoeliasf** [comment]
Referências
CAMPOS, Fernanda. Educação e Tecnologia: Ferramentas digitais no ensino básico. São Paulo: Editora Tecnoeduc, 2019.
MOURA, João. Lógica de Programação: Introdução e práticas para o ensino básico. Rio de Janeiro: Editora Alpha, 2020.
SANTOS, Maria. Inclusão Digital nas Escolas Públicas: Desafios e oportunidades no Brasil. Porto Alegre: Editora Educare, 2021.
UNESCO. Relatório Global sobre Educação e Tecnologia. 2022. Disponível em: https://unesco.org/. Acesso em: 9 set. 2024.
VALENTE, José Armando. Aprender com Tecnologias: O impacto da programação no desenvolvimento de habilidades cognitivas. Campinas: Papirus, 2017.

**Comment by pedrosarto** [comment]
gostei .
